<?php
$el_signo = $_REQUEST['el_signo'];

switch ($el_signo);
{
	case 1: echo "<h2>Aries: 21 de marzo al 20 de abril, </h2><br> Un Aries es una persona llena de energía y entusiasmo. Pionero y aventurero, le encantan los retos, la libertad y las nuevas ideas. A los Aries les gusta liderar y prefieren dar instrucciones a recibirlas. Son independientes y preocupados por su propia ambición y objetivos. Tienen una energía envidiable que a veces les lleva a ser agresivos, inquietos, argumentativos, tercos. Es fácil ofender a los Aries y, cuando se sienten ofendidos, es difícil hacer las paces con ellos. Aries es el primer signo del zodiaco y, en este sentido, su papel es empezar algo y liderar. Si un Aries empieza a creer en una buena causa, luchará sin descanso para promocionarla.";
	break;
	case 2: echo "<h2>Tauro: 21 de abril al 21 de mayo</h2><br> Un Tauro suele ser práctico, decidido y tener una gran fuerza de voluntad. Los Tauro son personas estables y conservadores, seguirán de forma leal un líder en el que tienen confianza. Les encanta la paz y tranquilidad y son muy respetuosos con las leyes y las reglas. Respetan los valores materiales y evitan las deudas. Son un poco reacios al cambio. Son más prácticos que intelectuales y, como les gusta la continuidad y la rutina, suelen ser de ideas fijas. Los Tauro son prudentes, estables y tienen un gran sentido de la justicia. No suelen hundirse ante las dificultades sino que siguen adelante hasta salir. A veces los Tauro pueden ser demasiado rígidos, argumentativos, egocéntricos y tercos. A los Tauro les gustan las cosas bellas y suelen ser aficionados al arte y la música."
	break;
	case 3: echo "<h2>Géminis: 22 de mayo al 21 de junio </h2><br> Géminis es el signo de los gemelos y, como tal, su carácter es doble, bastante complejo y contradictorio. Por un lado es versátil, pero por el otro puede ser insincero. Suelen tener elegancia y caer en los errores de los jóvenes. Tienen la felicidad, el egocentrismo, la imaginación y la inquietud de los niños. Los Géminis empiezan nuevas actividades y retos con entusiasmo, pero muchas veces les falta la constancia para realizarlos. Consideran que la vida es como un juego y buscan la diversión y nuevas situaciones. Un Géminis suele ser cortés, cariñoso, amable y generoso. A veces utilizan sus atributos para conseguir sus propios objetivos y son capaces de recurrir a la mentira sin perder su encanto con tal de obtener lo que quieren.";
	break;
	case 4: echo "<h2>Cáncer: 22 de junio al 22 de julio </h2><br> El carácter de un Cáncer es el menos claro de todos los signos del zodiaco. Un Cáncer puede ser desde tímido y aburrido hasta brillante y famoso. Los Cáncer son conservadores y les encanta la seguridad y el calor de su hogar. De hecho, para los hombres Cáncer, su hogar es como un nido, un refugio donde ir cuando el estrés de su trabajo es demasiado. La casa de un Cáncer tiende a ser su refugio personal más que un escaparate para deslumbrar a los demás. Un Cáncer entiende que hay momentos para ser sociable y otros momentos para ser solitario. Esto es una de las contradicciones en su carácter.</h2>";
	break;
	case 5: echo "<h2>Leo: 23 de julio al 22 de agosto</h2> <br> Un Leo es el signo más dominante del zodiaco. También es creativo y extrovertido. Son los reyes entre los humanos, de la misma forma que los leones son los reyes en el reino animal. Tienen ambición, fuerza, valentía, independencia y total seguridad en sus capacidades. No suelen tener dudas sobre qué hacer. Son líderes sin complicaciones, saben dónde quieren llegar y ponen todo su empeño, energía y creatividad en conseguir su objetivo. No temen los obstáculos, más bien crecen ante ellos. En general son buenos, idealistas e inteligentes. Pueden llegar a ser tercas en sus creencias, pero siempre desde una fe y sinceridad absoluta. A un Leo le suelen gustar el lujo y el poder. ";
	break;
	case 6: echo "<h2>Virgo: 23 de agosto al 22 de septiembre</h2><br> Virgo, el único signo representado por una mujer, es un signo caracterizado por su precisión, su convencionalidad, su actitud reservada y su afán, a veces hasta obsesión, con la limpieza. Los Virgo suelen ser observadores y pacientes. Pueden parecer a veces fríos, de hecho les cuesta hacer grandes amigos. El hecho que muchas de sus relaciones con otros resultan ser superficiales es porque en realidad los Virgo temen dar riendas a sus sentimientos y les falta tener seguridad en sus emociones y opiniones. Prefieren actuar con reservas y con una disposición agradable. Suelen ser discretos, amables y divertidos con otras personas y pueden ayudar a resolver los problemas de terceros con una habilidad y sensatez que muchas veces les falta en sus propias relaciones personales.</h2>";
		break;
	case 7: echo "<h2>Libra: 23 de septiembre al 22 de octubre</h2><br> Los Libra se encuentran entre los signos más civilizados del zodiaco. Tienen encanto, elegancia y buen gusto, son amables y pacíficos. Les gusta la belleza y la armonía y son capaces de ser imparciales ante conflictos. No obstante, una vez que han llegado a una opinión sobre algo, no les gusta que se les contradiga. Les gusta contar con el apoyo de los demás. Un Libra tiende a ser sensible a las necesidades de los demás y suele ser muy sociable. No soportan el conflicto y la crueldad y son muy diplomáticos ante los conflictos. Suelen buscar el consenso ante una situación conflictiva. Saben valorar los esfuerzos de los demás y les gusta vivir y trabajar en equipo. El lado negativo de un Libra es frívolo y es fácil que cambiar de opinión o de lealtades. No les gusta la rutina y muchas veces les falta la capacidad de enfrentarse a los demás. Les encanta el placer y esto les puede llevar a cometer ciertos excesos en su vida. Son muy curiosos, lo que puede ser una virtud si lo invierten en descubrir nuevas cosas, pero también un defecto si les lleva a meterse demasiado en la vida o los asuntos de los demás. ";
		# code...
		break;
	case 8: echo "<h2>Escorpio: 23 de octubre al 22 de noviembre</h2><br> El Escorpio es un signo intenso con una energía emocional única en todo el zodiaco. Aunque puedan aparecer tranquilos, los Escorpio tienen una agresión y magnetismo interno escondidos dentro. Son afables, buenos tertulianos, reservados y cortés, pero aunque parezcan estar algo retirados del centro de actividad, en realidad están observando todo con su ojo crítico. El Escorpio es tremendamente poderoso y su carácter puede causar enormes beneficios o grandes riesgos para los demás. Su tenacidad y fuerza de voluntad son únicas pero, sin embargo, son muy sensibles y fácilmente afectados por las circunstancias que les rodean. Son emocionales y fácilmente heridos o aludidos. De hecho, pueden perder totalmente el genio al percibir, incluso erróneamente, que alguien les ha insultado. No saben morderse la lengua y pueden ser muy críticos. Si un Escorpio logra utilizar su enorme energía de forma constructiva es un gran activo para la sociedad y se puede convertir en un gran líder. No obstante, los Escorpio deben aprender a controlarse, porque pueden llegar a ser demasiado críticos y resentidos con los demás. Son excelentes amigos de los que consideran merecen su respeto.";
		# code...
		break;
	case 9: echo "<h2>Sagitario: 23 de noviembre al 21 de diciembre</h2><br> El Sagitario es uno de los signos más positivos del zodiaco. Son versátiles y les encanta la aventura y lo desconocido. Tienen la mente abierta a nuevas ideas y experiencias y mantienen una actitud optimista incluso cuando las cosas se les ponen difíciles. Son fiables, honestos, buenos, sinceros y dispuestos a luchar por buenas causas, cueste lo que cueste. Los Sagitario suelen creer en la ética y les gusta seguir los ritos de la religión, de un partido político o de una organización. Esto les puede llevar a tener ciertas tendencias supersticiosas a veces. Les encanta abarcar nuevos proyectos y aprender sobre cosas nuevas. Son intuitivos y buenos organizadores y, aunque son generosos, también son muy cuidadosos, lo que les convierte en buenos gestores de situaciones y proyectos. Algunos Sagitario tienen un gran genio que puede aparecer ante situaciones que para los demás carecen de importancia. También pecan de impaciencia cuando los demás no van al mismo paso que ellos. Son capaces de sacrificarse para realizar un objetivo. Esto hace que a veces son demasiado exigentes con los demás. ";
		# code...
		break;
	case 10: echo "<h2>Capricorno: 22 de diciembre al 20 de enero</h2><br> Un Capricornio es un de los signos del zodiaco más estables, seguros y tranquilos. Son trabajadores, responsables, prácticos y dispuestos a persistir hasta sea necesario para conseguir su objetivo. Son fiables y muchas veces tienen el papel de terminar un proyecto iniciado por uno de los signos más pioneros. Les encanta la música. Un Capricornio exige mucho de sus empleados, familiares y amigos, pero solo porque se lo exige también a si mismo. Suelen ser personas justas. No se encuentran entre los signos del zodiaco más felices. Más bien tienden a veces hacia el melancolizo y pesimismo. Cuando un Capricornio sufre depresión debe buscar ayuda. De hecho, un Capricornio debe siembre intentar mantener una estabilidad emocional a través de la meditación, respiración o actividades que le ayudan a relajarse y no perder control de sus emociones. ";
		# code...
		break;
	case 11: echo "<h2>Acuario: 21 de enero al 19 de febrero</h2><br> Los Acuario tienen una personalidad fuerte y atractiva. Hay dos tipos de Acuario: uno es tímido, sensible, y paciente. El otro tipo es exuberante, vivo y puede llegar a esconder las profundidades de su personalidad debajo de un aire frívolo. Ambos tipos de Acuario tienen una fuerza de convicción y de la verdad muy fuerte y son tan honestos que saben cambiar sus opiniones si aparecen pruebas que muestran lo contrario de lo que pensaban antes. Los Acuario son capaces de ver los dos lados de un argumento por lo que son uno de los signos más tolerantes y sin prejuicios de todo el zodiaco. Están abiertos a la verdad y dispuestos a aprender de todos. Un Acuario es humano, sincero, refinado e idealista. Saben ser perseverantes y expresarse con razón, moderación y, a veces, humor. Casi todos los Acuario son inteligentes, claros y lógicos. Muchos son imaginativos y psíquicos. A veces sienten la necesidad de retirarse del mundo para meditar o pensar. Se niegan a seguir la multitud. A pesar de la personalidad abierta de los acuarios y de su deseo de ayudar a la humanidad, no suelen hacer amigos con facilidad. No se entregan su alma con facilidad. ";
		# code...
		break;
	case 12: echo "<h2>Piscis: 20 de febrero al 20 de marzo</h2><br> Un Piscis tiene una personalidad tranquila, paciente y amable. Son sensibles a los sentimientos de los demás y responden con simpatía y tacto al sufrimiento de los demás. Son muy queridos por los demás porque tienen un carácter afable, cariñoso y amable, y no suponen una amenaza para los que quieren tener puestos de autoridad o mayor popularidad. Suelen asumir su entorno y sus circunstancias y no suelen tomar la iniciativa para resolver problemas. Les preocupan más los problemas de otros que sus propios problemas. Los Piscis tienden a existir de forma emocional más que de forma racional, de forma instintiva más que de forma intelectual. No les gusta sentirse confinados y no respetan las convenciones así por las buenas. Pero tampoco tienen la energía o la motivación para luchar contra el poder establecido. Los Piscis muchas veces se retiran hacia un mundo de sueños en el que sus capacidades pueden aportarles beneficios. Tienen una gran capacidad creativa artística. ";
		# code...
		break;
	default: echo "Seleccione un signo del zodiaco";
	break;
}
?>